server {
  listen 80;

  # --- Task 2: Cache Static Assets ---
  # This block targets files that don't change often (JS, CSS, Images, Fonts)
  # Since Vite uses "content hashing" (filenames change when you update code), 
  # we can safely cache these for a long time (1 year).
  location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg)$ {
    root /usr/share/nginx/html;
    expires 1y;
    add_header Cache-Control "public, no-transform";
    access_log off; # Reduces server load by not logging every image/js request
  }

  location /api {
    # On AWS, we will name the backend container "backend"
    proxy_pass http://backend:8000; 
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';
    proxy_set_header Host $host;
    proxy_cache_bypass $http_upgrade;
  }

  location / {
    root /usr/share/nginx/html;
    index index.html;
    
    # --- Task 2: Prevent index.html Caching ---
    # We want the browser to ALWAYS check if there is a new version of index.html
    # so that users get your code updates immediately.
    add_header Cache-Control "no-store, no-cache, must-revalidate";
    
    try_files $uri $uri/ /index.html;
  }
}